apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-postgrest-api
  namespace: argocd
spec:
  destination:
    namespace: api-auth
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/postgrest-api
    repoURL: git@github.com:muntashir-islam/postgrest-api-eks.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true