---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  role: k8s-test
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: k8s-test
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: k8s-test
  tags:
    karpenter.sh/discovery: k8s-test
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      # requirements:
      #   - key: "karpenter.k8s.aws/instance-category"
      #     operator: In
      #     values: ["m", "r"]
      #   - key: "karpenter.k8s.aws/instance-cpu"
      #     operator: In
      #     values: ["2", "4"]
      #   - key: "karpenter.k8s.aws/instance-hypervisor"
      #     operator: In
      #     values: ["nitro"]
      #   - key: "karpenter.k8s.aws/instance-generation"
      #     operator: Gt
      #     values: ["2"]
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["m5.large"]
  limits:
    cpu: 10
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s