# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: filebeat-config
#   namespace: log
# data:
#   filebeat.yml: |
#     filebeat.inputs:
#       - type: container
#         paths:
#           - /var/log/containers/*.log
#         json.message_key: log
#         json.keys_under_root: true
#         multiline.pattern: '^[[:space:]]'
#         multiline.negate: false
#         multiline.match: after
#     processors:
#     - add_kubernetes_metadata:
#         in_cluster: true
#     - drop_event:
#           when:
#             or:
#               - contains:
#                   kubernetes.namespace: "ingress-nginx"
#               - contains:
#                   kubernetes.namespace: "kube-system"
#               - contains:
#                   kubernetes.namespace: "log"
#               - contains:
#                   kubernetes.namespace: "monitoring"
#     output.elasticsearch:
#       hosts: ["elasticsearch:9200"]
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: log
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        json.message_key: log
        json.keys_under_root: true
        multiline.pattern: '^[[:space:]]'
        multiline.negate: false
        multiline.match: after

    processors:
      - add_kubernetes_metadata:
          in_cluster: true
      # Drop everything NOT from api-auth
      - drop_event:
          when:
            not:
              equals:
                kubernetes.namespace: "api-auth"

    output.elasticsearch:
      hosts: ["elasticsearch:9200"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: log
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: default
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.17.16
        args: ["-e", "-strict.perms=false"]
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
